name: Build and Upload Java App Artifact

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - build-triggered

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean install

    - name: Generate Artifact
      run: |
        mkdir -p artifacts
        cp target/your-java-app.jar artifacts/
      working-directory: ${{ github.workspace }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: java-app-artifact
        path: artifacts/your-java-app.jar
