name: Deploy application 
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - build-triggered

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
  deploy_to_DEV:
    runs-on: ubuntu-20.04  # Specify a specific version of Ubuntu
    needs: build  # Ensure the 'build' job completes before deploying

    steps:
      - name: Copy Artifact to Runner
        run: cp ./target/onlinebookstore.war $GITHUB_WORKSPACE

      - name: Verify Deployed Artifact
        run: ls -l $GITHUB_WORKSPACE/onlinebookstore.war
