name: Build and Upload Java App Artifact

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - build-triggered

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean install

    - name: Deploy File to VM
      run: |
        scp -i ${{ secrets.VM_SSH_KEY }} ./target/onlinebookstore.war ubuntu@44.217.154.0:/home/ubuntu/Nishika_github/DEV
    env:
      VM_SSH_KEY: ${{ secrets.BASTION_PASSWORD }}
