name: Deploy application 
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # This uses the latest LTS version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build Artifact
        run: mvn clean package  # Adjust this to your build command

  deploy:
    runs-on: ubuntu-20.04  # Specify a specific version of Ubuntu

    needs: build  # Ensure the 'build' job completes before deploying

    steps:
      - name: Copy Artifact to Runner
        run: cp target/onlinebookstore.war $GITHUB_WORKSPACE

      - name: Verify Deployed Artifact
        run: ls -l $GITHUB_WORKSPACE/onlinebookstore.war
