name: Build Java App with Maven

on:
  workflow_dispatch:  # Manual trigger is done 
  repository_dispatch:
    types:
      - build-triggered
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Adjust the Java version if needed

    - name: Build with Maven
      run: mvn clean install
