name: Build and Upload Java App Artifact

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - build-triggered

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to DEV
      uses: appleboy/ssh-action@v0.3.0
      env:
        host: ${{ secrets.BASTION_HOST }}
        username: ${{ secrets.BASTION_USERNAME }}
        password: ${{ secrets.BASTION_PASSWORD }}  # Use an SSH key for security
     
      with: 
           source: "./target/onlinebookstore.war"
           target: "/home/ubuntu/Nishika_github/DEV"
