name: Move new issues to Backlog
on:
  issues:
    types: [opened]
jobs:
  move-to-backlog:
    runs-on: ubuntu-latest
    steps:
      - name: Move to Backlog
        uses: fojia/action-move-issues-to-column@master
        with:
          project: 'Onlinebookstore ALM Dashboard'
          column: 'Backlog'
          owner: 'ALM-Github-ORG'
          repo: 'Onlinebookstore_ALM'
          type: 'repo'
          github_token: ${{ secrets.GITHUB_TOKEN }}

