name: sonarqube_analysis

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - build-triggered

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build Artifact
        run: mvn clean package

  analyze:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Install SonarScanner
        run: |
         sudo apt-get update
         sudo apt-get install -y unzip wget openjdk-11-jre-headless
         sudo wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
         sudo unzip -o sonar-scanner-cli-4.6.2.2472-linux.zip -d /opt
         sudo rm sonar-scanner-cli-4.6.2.2472-linux.zip
         sudo find /opt/sonar-scanner-4.6.2.2472-linux -type l -exec sh -c 'cp --remove-destination "$(readlink -f "$0")" "$0"' {} \;
         echo "export PATH=/opt/sonar-scanner-4.6.2.2472-linux/bin:\$PATH" >> $GITHUB_ENV

      - name: Sonar Scanner Version
        run: |
          /opt/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner --version
          
      - name: Sonar Scan
        run: |
          /opt/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
            -Dsonar.projectKey=Onlinebookstore_ALM \
            -Dsonar.host.url=http://20.96.199.229:9000/ \
            -Dsonar.login=${{ secrets.SONAR_SECRET }}
            -e -X
