name: sonarqube_analysis

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - build-triggered

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build Artifact
        run: mvn clean package

  analyze:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Download SonarQube Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
          unzip sonar-scanner-cli-4.6.0.2311-linux.zip
          export PATH=$PATH:$PWD/sonar-scanner-4.6.0.2311-linux/bin

      - name: SonarQube Analysis
        run: |
          mvn clean package sonar:sonar \
            -Dsonar.projectKey=Onlinebookstore_ALM \
            -Dsonar.host.url=https://20.96.199.229:9000/ \
            -Dsonar.login=${{ secrets.SONAR_SECRET }}
